# Generated by Django 4.1.4 on 2022-12-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_recruiter",
            field=models.BooleanField(default=False),
        ),
    ]
