# Generated by Django 4.1.4 on 2022-12-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_userprofile_companay_userprofile_designation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="uniqueCode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
