# Generated by Django 4.1.4 on 2022-12-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_userprofile_uniquecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.FileField(blank=True, null=True, upload_to="Profile_pic"),
        ),
    ]
