# Generated by Django 4.1.4 on 2022-12-08 07:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(null=True)),
                ("email", models.EmailField(max_length=200, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                (
                    "jobtype",
                    models.CharField(
                        choices=[
                            ("Permanent", "Permanent"),
                            ("Temporary", "Temporary"),
                            ("Intership", "Intership"),
                        ],
                        default="Permanent",
                        max_length=200,
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("HighSchool", "Highschool"),
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("Doctorate", "Doctorate"),
                            ("Phd", "Phd"),
                        ],
                        default="HighSchool",
                        max_length=200,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("Busienss", "Busienss"),
                            ("Information Technology", "It"),
                            ("Banking", "Banking"),
                            ("Education/Training", "Education"),
                            ("Telecommunication", "Telecommunication"),
                            ("Engineering", "Engineering"),
                            ("Health", "Health"),
                            ("Media", "Media"),
                            ("Others", "Others"),
                        ],
                        default="Busienss",
                        max_length=200,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("No Experince", "No Experince"),
                            ("1 Year", "One Year"),
                            ("2 Years", "Two Years"),
                            ("3 Years Plus", "Three Year Plus"),
                        ],
                        default="No Experince",
                        max_length=200,
                    ),
                ),
                (
                    "salary",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                ("positions", models.IntegerField(default=1)),
                ("company", models.CharField(max_length=200, null=True)),
                ("lastDate", models.DateTimeField(default=job.models.return_date_time)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
