# Generated by Django 4.1.4 on 2022-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_job_google_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="google_map",
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
