# Generated by Django 4.1.4 on 2022-12-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_job_google_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="jobtype",
            field=models.CharField(
                choices=[
                    ("Permanent", "Permanent"),
                    ("Temporary", "Temporary"),
                    ("Intenrship", "Intenrship"),
                ],
                default="Permanent",
                max_length=200,
            ),
        ),
    ]
