# Generated by Django 4.1.4 on 2022-12-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_alter_job_jobtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(
                choices=[
                    ("No Experience", "No Experince"),
                    ("1 Year", "One Year"),
                    ("2 Years", "Two Years"),
                    ("3 Years Plus", "Three Year Plus"),
                ],
                default="No Experience",
                max_length=200,
            ),
        ),
    ]
