# Generated by Django 4.1.4 on 2022-12-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_canidatesapplied_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canidatesapplied",
            name="status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
